// Real Solana AI agent tokens with verified on-chain contract addresses.
// Scores & chain_activity are seed values — live scans via Helius/DexScreener
// will overwrite them when users click through to the detail panel.

export const MOCK_AGENTS = [
  {
    id: 1,
    name: "ai16z",
    ticker: "$AI16Z",
    address: "HeLp...jwC",
    fullAddress: "HeLp6NuQkmYB4pYWo2zYs22mESHXPQYzXbB8n4V98jwC",
    verified: true,
    score: 91,
    category: "AI Trading DAO",
    description:
      "Decentralized AI-powered trading fund on Solana. Uses a network of AI agents and community DAO governance to execute and optimise cross-protocol trading strategies. Built on ElizaOS.",
    chain_activity: {
      txCount: 84200,
      lastTx: "1 min ago",
      contractCalls: 21300,
      uniqueInteractions: 9800,
    },
    code_verified: true,
    social: {
      twitter: "@ai16zdao",
      followers: "210K",
      github: "elizaOS/eliza",
      stars: 17600,
    },
    checks: {
      onchain: true,
      codeAudit: true,
      socialProof: true,
      aiInference: true,
      governance: true,
    },
    launchDate: "2024-10-25",
    mcap: "$320M",
    volume24h: "$28M",
    logo: "A",
  },
  {
    id: 2,
    name: "GRIFFAIN",
    ticker: "$GRIFFAIN",
    address: "KENJ...vEP",
    fullAddress: "KENJSUYLASHUMfHyy5o4Hp2FdNqZg1AsUPhfH2kYvEP",
    verified: true,
    score: 88,
    category: "DeFi Agent",
    description:
      "On-chain AI intelligence engine for autonomous DeFi operations. Handles wallet management, token trading, NFT minting, and predictive yield strategies via ML inference on Solana mainnet.",
    chain_activity: {
      txCount: 52400,
      lastTx: "3 min ago",
      contractCalls: 14800,
      uniqueInteractions: 4200,
    },
    code_verified: true,
    social: {
      twitter: "@griffain_ai",
      followers: "48K",
      github: "griffain-protocol",
      stars: 920,
    },
    checks: {
      onchain: true,
      codeAudit: true,
      socialProof: true,
      aiInference: true,
      governance: false,
    },
    launchDate: "2024-11-08",
    mcap: "$280M",
    volume24h: "$41M",
    logo: "G",
  },
  {
    id: 3,
    name: "ARC",
    ticker: "$ARC",
    address: "61V8...pump",
    fullAddress: "61V8vBaqAGMpgDQi4JcAwo1dmBGHsyhzodcPqnEVpump",
    verified: true,
    score: 84,
    category: "AI Infrastructure",
    description:
      "AI Rig Complex — containerised execution environment for autonomous agents. Provides the Rig Framework (Rust) toolkit for building LLM applications and agent pipelines on-chain.",
    chain_activity: {
      txCount: 39100,
      lastTx: "5 min ago",
      contractCalls: 11200,
      uniqueInteractions: 3600,
    },
    code_verified: true,
    social: {
      twitter: "@arc_rig",
      followers: "31K",
      github: "0xPlaygrounds/rig",
      stars: 2800,
    },
    checks: {
      onchain: true,
      codeAudit: true,
      socialProof: true,
      aiInference: true,
      governance: false,
    },
    launchDate: "2024-12-01",
    mcap: "$95M",
    volume24h: "$12M",
    logo: "A",
  },
  {
    id: 4,
    name: "ZEREBRO",
    ticker: "$ZEREBRO",
    address: "8x5V...2Wn",
    fullAddress: "8x5VqbmXgMjcnJGLjCEe6tHDvMhvxmKZaC6Jo2Wn",
    verified: true,
    score: 79,
    category: "Autonomous Agent",
    description:
      "Smart agent prominent on Crypto Twitter known for autonomous artistic creation — music, memes, artworks, and NFTs. Operates independently across X, Discord and on-chain with swarm coordination.",
    chain_activity: {
      txCount: 28700,
      lastTx: "12 min ago",
      contractCalls: 7400,
      uniqueInteractions: 2900,
    },
    code_verified: true,
    social: {
      twitter: "@0xzerebro",
      followers: "89K",
      github: "zerebro-agent",
      stars: 1400,
    },
    checks: {
      onchain: true,
      codeAudit: true,
      socialProof: true,
      aiInference: "partial",
      governance: false,
    },
    launchDate: "2024-11-20",
    mcap: "$78M",
    volume24h: "$8.2M",
    logo: "Z",
  },
  {
    id: 5,
    name: "GOAT",
    ticker: "$GOAT",
    address: "9Tb2...xvzw",
    fullAddress: "9Tb2ohu5p16bpbarqd3n27wnkf51ukfs8z1gzzldxvzw",
    verified: "pending",
    score: 62,
    category: "Meme Agent",
    description:
      "Goatseus Maximus — first token explicitly endorsed by the Truth Terminal AI agent. Launched via pump.fun Oct 2024. Peaked at $1B market cap. More meme than agent infrastructure.",
    chain_activity: {
      txCount: 91000,
      lastTx: "8 min ago",
      contractCalls: 4200,
      uniqueInteractions: 18400,
    },
    code_verified: false,
    social: {
      twitter: "@truth_terminal",
      followers: "142K",
      github: null,
      stars: 0,
    },
    checks: {
      onchain: true,
      codeAudit: false,
      socialProof: true,
      aiInference: false,
      governance: false,
    },
    launchDate: "2024-10-10",
    mcap: "$450M",
    volume24h: "$52M",
    logo: "G",
  },
  {
    id: 6,
    name: "VVAIFU",
    ticker: "$VVAIFU",
    address: "FQ1t...p8",
    fullAddress: "FQ1tyso61AH1tzodyJfSwmzsD3GToybbRNoZxUBz21p8",
    verified: "pending",
    score: 67,
    category: "Agent Protocol",
    description:
      "Protocol for creating, managing and interacting with persistent AI agents on-chain. $VVAIFU is the core utility and governance token enabling agent ownership and monetisation.",
    chain_activity: {
      txCount: 19300,
      lastTx: "22 min ago",
      contractCalls: 5800,
      uniqueInteractions: 2100,
    },
    code_verified: false,
    social: {
      twitter: "@vvaifu_fun",
      followers: "24K",
      github: "vvaifu-protocol",
      stars: 340,
    },
    checks: {
      onchain: true,
      codeAudit: false,
      socialProof: true,
      aiInference: "partial",
      governance: false,
    },
    launchDate: "2024-11-15",
    mcap: "$42M",
    volume24h: "$5.1M",
    logo: "V",
  },
  {
    id: 7,
    name: "DEGENAI",
    ticker: "$DEGENAI",
    address: "Gu3L...pump",
    fullAddress: "Gu3LDkn7Vx3bmCzLafYNKcDxv2mH7YN44NJZFXnypump",
    verified: "pending",
    score: 58,
    category: "Trading Agent",
    description:
      "Degen-focused autonomous AI trading agent built on the Dolos architecture. Executes high-frequency memecoin trades with satirical commentary. Partial on-chain AI inference detected.",
    chain_activity: {
      txCount: 14800,
      lastTx: "45 min ago",
      contractCalls: 3900,
      uniqueInteractions: 1200,
    },
    code_verified: false,
    social: {
      twitter: "@degenspartanai",
      followers: "18K",
      github: null,
      stars: 0,
    },
    checks: {
      onchain: "partial",
      codeAudit: false,
      socialProof: true,
      aiInference: false,
      governance: false,
    },
    launchDate: "2024-12-18",
    mcap: "$28M",
    volume24h: "$3.4M",
    logo: "D",
  },
  {
    id: 8,
    name: "TARS AI",
    ticker: "$TAI",
    address: "Hax9...gdD",
    fullAddress: "Hax9LTgsQkze1YFychnBLtFH8gYbQKtKfWKKg2SP6gdD",
    verified: "pending",
    score: 54,
    category: "Market Agent",
    description:
      "TARS AI Market on Solana — agent interactions and trading platform. Provides real-time market analysis, token sentiment scoring and autonomous trade routing.",
    chain_activity: {
      txCount: 9200,
      lastTx: "1 hr ago",
      contractCalls: 2400,
      uniqueInteractions: 880,
    },
    code_verified: false,
    social: {
      twitter: "@tars_ai_sol",
      followers: "11K",
      github: "tars-ai",
      stars: 180,
    },
    checks: {
      onchain: "partial",
      codeAudit: false,
      socialProof: true,
      aiInference: false,
      governance: false,
    },
    launchDate: "2025-01-04",
    mcap: "$19M",
    volume24h: "$2.1M",
    logo: "T",
  },
  {
    id: 9,
    name: "SOLAI",
    ticker: "$SOLAI",
    address: "Hzwe...zsd",
    fullAddress: "Hzwejbyk7kPk5REaxiZZFAxF5o6gF5GrK3aatEPoSzsd",
    verified: false,
    score: 31,
    category: "AI Access",
    description:
      "Decentralised platform offering on-chain access to AI models (GPT-4, Claude, Gemini) via Solana payments. Claims no-KYC unlimited inference. Smart contract activity is sparse.",
    chain_activity: {
      txCount: 2100,
      lastTx: "3 days ago",
      contractCalls: 480,
      uniqueInteractions: 210,
    },
    code_verified: false,
    social: {
      twitter: "@solai_ag",
      followers: "6.2K",
      github: null,
      stars: 0,
    },
    checks: {
      onchain: false,
      codeAudit: false,
      socialProof: "partial",
      aiInference: false,
      governance: false,
    },
    launchDate: "2024-11-22",
    mcap: "$4.8M",
    volume24h: "$290K",
    logo: "S",
  },
  {
    id: 10,
    name: "CYBERTRADER",
    ticker: "$CYB",
    address: "ajto...f4q",
    fullAddress: "ajtopmxbczbd2qc3yltunhsia6fg3etpeu2g1a4juf4q",
    verified: false,
    score: 22,
    category: "Trading Bot",
    description:
      "Intelligent AI trading assistant for Solana. Analyses tokens, reads market sentiment and claims autonomous execution. On-chain activity does not match claimed AI inference volume.",
    chain_activity: {
      txCount: 1400,
      lastTx: "5 days ago",
      contractCalls: 210,
      uniqueInteractions: 88,
    },
    code_verified: false,
    social: {
      twitter: "@cybertrader_ai",
      followers: "3.8K",
      github: null,
      stars: 0,
    },
    checks: {
      onchain: false,
      codeAudit: false,
      socialProof: false,
      aiInference: false,
      governance: false,
    },
    launchDate: "2025-02-10",
    mcap: "$1.2M",
    volume24h: "$48K",
    logo: "C",
  },
  {
    id: 11,
    name: "VIRTUAL",
    ticker: "$VIRTUAL",
    address: "3iQL...r9y",
    fullAddress: "3iQL8BFS2vE7mww4ehAqQHAsbmRNCrPxizWAT2Zfyr9y",
    verified: true,
    score: 82,
    category: "Agent Platform",
    description:
      "Monetisation and coordination layer for autonomous AI agents. Expanded from Base to Solana for faster execution and deeper meme/agent liquidity. Powers dozens of agent token launches.",
    chain_activity: {
      txCount: 44600,
      lastTx: "7 min ago",
      contractCalls: 12100,
      uniqueInteractions: 5800,
    },
    code_verified: true,
    social: {
      twitter: "@virtuals_io",
      followers: "98K",
      github: "Virtual-Protocol",
      stars: 1200,
    },
    checks: {
      onchain: true,
      codeAudit: true,
      socialProof: true,
      aiInference: "partial",
      governance: true,
    },
    launchDate: "2024-09-14",
    mcap: "$180M",
    volume24h: "$19M",
    logo: "V",
  },
  {
    id: 12,
    name: "ELIZA",
    ticker: "$ELIZA",
    address: "U71h...eyx",
    fullAddress: "U71hPHrnG3mNJzTHyK1rmuNzySs97pnoGbwX3t5xeyx",
    verified: true,
    score: 86,
    category: "Agent Framework",
    description:
      "De-facto Linux layer for on-chain AI agents. Open-source TypeScript framework with 200+ plugins, 17,600+ GitHub stars. Unified message bus across X, Discord, Telegram, and Solana on-chain.",
    chain_activity: {
      txCount: 38900,
      lastTx: "4 min ago",
      contractCalls: 9800,
      uniqueInteractions: 7200,
    },
    code_verified: true,
    social: {
      twitter: "@elizaos",
      followers: "95K",
      github: "elizaOS/eliza",
      stars: 17600,
    },
    checks: {
      onchain: true,
      codeAudit: true,
      socialProof: true,
      aiInference: true,
      governance: false,
    },
    launchDate: "2024-10-28",
    mcap: "$140M",
    volume24h: "$15M",
    logo: "E",
  },
];

export const PLATFORM_STATS = {
  totalScanned: MOCK_AGENTS.length,
  certified: MOCK_AGENTS.filter((a) => a.verified === true).length,
  larpsDetected: MOCK_AGENTS.filter((a) => a.verified === false && a.score < 30).length,
  avgTrustScore: Math.round(
    MOCK_AGENTS.reduce((s, a) => s + a.score, 0) / MOCK_AGENTS.length
  ),
};
